name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  Tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Test
        run: |
          go test .
