name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  Run Tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Formatting
        run: |
          test "0" = $(gofmt -l .| wc -l)
      - name: UnitTests
        run: |
          go test .
