name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Formatting Test
        run: |
          test "0" = $(gofmt -l .| wc -l)
      - name: Unit Test
        run: |
          go test -race -covermode=atomic -coverprofile=coverage.out -covermode=atomic
